canonical/sdcore-upf-k8s-operator

.github/workflows/promote.yaml
.github/workflows/publish-charm.yaml
.github/workflows/push.yaml

Uses `upload-charm` workflow to publish charm.

Uses `upload-charm` workflow to publish charm

---

README.md
metadata.yaml
src/charm.py

- Standardises around `SD-Core` naming
- Use badges in README.md

Standardises around `SD-Core` naming

---

lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py
tests/unit/test_charm.py

Uses multus lib 0.2

---

README.md
lib/charms/kubernetes_charm_libraries/v0/multus.py
metadata.yaml
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Various improvements to the UPF operator to make it properly serve traffic to UE's:
- Uses most recent version of Multus library
- Separates workload configuration in independent "pebble_ready" events
- Leverages NetworkAttachmentDefinition to create one of the routes
Also reduces charm complexity:
- Removes unused web container

[Bug fix] Improvements to the UPF operator

---

src/charm.py
tests/unit/test_charm.py

Do not run bessctl up4 configuration twice in sdcore-upf-operator.
This patch creates a dummy file when bessctl configure is executed. So, bessctl configure command is executed once.
Fixing FileNotFoundError error while getting namespace through the file: "/var/run/secrets/kubernetes.io/serviceaccount/namespace" during the k8s service patcher creation.

bessctl up4 configuration is executed once

---

requirements.txt
test-requirements.txt

Removes version pins for:
- Juju 
- Pydentic
- Ops

Unpinning Python dependency versions

---

.github/workflows/main.yaml
config.yaml
metadata.yaml
src/charm.py
tests/unit/expected_upf.json
tests/unit/test_charm.py

Implements provider side of the `fiveg_n4` relation.
Reference:
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit#heading=h.baow5ofrt61k

Telco 724 implementing fiveg n4 provider

---

lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py
tests/unit/test_charm.py

This PR updates the multus library to include the fix for https://github.com/canonical/kubernetes-charm-libraries/issues/16 and implements the necessary changes in the charm part.

Use custom event to trigger multus configuration

---

lib/charms/kubernetes_charm_libraries/v0/hugepages_volumes_patch.py

Update HugePages library

---

lib/charms/kubernetes_charm_libraries/v0/multus.py

Updates to the latest version of multus library to address #54 
- N/A My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- N/A I have performed a self-review of my own code
- N/A I have made corresponding changes to the documentation
- N/A I have added tests that validate the behaviour of the software
- N/A I validated that new and existing unit tests pass locally with my changes
- N/A I have bumped the version of the library

fix: TELCO-887 Updating multus lib

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/main.yaml
terraform/README.md
terraform/main.tf
terraform/outputs.tf
terraform/terraform.tf
terraform/variables.tf

Adds Terraform module for UPF.

feat: Adding Terraform module for UPF

---

charmcraft.yaml

Remove unnecessary content from charm build

chore: Remove unnecessary content from charm build

---

src/charm.py
tests/unit/test_charm.py

This PR aims to fix #99. The proposed solution is to wrap all the interactions within the `bessd` container in a try-except block, as recommended in [juju SDK](https://juju.is/docs/sdk/container-name-pebble-ready-event).

fix: handle ConnectionError in pebble-ready event

---

src/charm.py
tests/unit/test_charm.py

Changes the bessd config check from file presence based to query process state.
N/A I have made corresponding changes to the documentation
N/A Any dependent changes have been merged and published in downstream modules
N/A I have bumped the version of the library

chore: Update configuration logic

---

README.md

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
N/A I have added tests that validate the behaviour of the software
N/A I validated that new and existing unit tests pass locally with my changes
N/A Any dependent changes have been merged and published in downstream modules
N/A I have bumped the version of the library

fix: Removing DPDK until it can be verified

---

.github/workflows/update-libs.yaml

This PR is a first attempt of adding automatic approval and merge for the update libs job.
It's hard to test it before it goes to main, so further fixes to the config might be needed.
NOTE:
If this works, the whole workflow will be moved to the common workflows repository.

chore: Adding steps for automatic PR approval and automerge in update-libs.yaml

---

.github/workflows/main.yaml
.github/workflows/promote.yaml
README.md
terraform/variables.tf

Updates project version to `1.5`

chore: Bumping project version to 1.5

---

src/charm.py
tests/unit/test_charm.py

This PR backports the fix from #241.
Full context available in the original PR.

fix: Blocks starting routectl if bess is not configured

---

src/charm.py
tests/unit/test_charm.py

When using DPDK, the MTU configuration was not applied. This PR fixes this.

fix: Add MTU to NAD when using DPDK

---

lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py

Use the latest multus library, simplifying how multus is managed. This new approach gets rid of the need of custom events.

chore: use multus lib 0.16

---

src/charm.py
tests/unit/test_charm_collect_status.py
tests/unit/test_charm_config_changed.py
tests/unit/test_charm_pfcp_agent_pebble_ready.py

Fixes the issue: https://github.com/canonical/sdcore-upf-k8s-operator/issues

fix: UPF pod stuck at waiting status for pfcp-agent service

---

.github/dependabot.yml
.github/workflows/1_5_scheduled_runs.yaml
.github/workflows/main.yaml
.github/workflows/promote.yaml
README.md
terraform/variables.tf

- Bumps project version to 1.6
- Adds scheduled CI runs for `v1.5`

chore: Updates versions for v1.6

---

charmcraft.yaml

chore: Bumps charm base to 24.04

---

lib/charms/kubernetes_charm_libraries/v0/multus.py

When doing changes in #441 I forgot to bump the lib version. This PR fixes it.

fix: Bumps lib version

---

lib/charms/kubernetes_charm_libraries/v0/multus.py

Fetches the updated lib rather than doing changes locally.

fix: Updates Multus in the correct way

---

src/charm.py

This PR is porting the fix from `main` to `v1.5`.
When `kube-apiserver` isn't ready, fetching list of K8s nodes fails with `Unauthorized` error. This fix handles such situation by catching the error and logging the relevant message rather than raising an error which puts the charm in the error state.

fix: Fixes Unauthorized error when listing K8s nodes

---

src/charm.py
tests/unit/test_charm_collect_status.py

The comparison of the amount of allocatable hugepages failed if the amount was not exactly "2Gi" because we were using string comparisons.
This PR properly converts to integers before making the comparison and adds tests for multiple values.

fix: Properly evaluate amount of hugepages
