.github/workflows/main.yaml
metadata.yaml
requirements.txt
src/charm.py
tests/unit/test_charm.py

Implements `fiveg_n3` provider side in the UPF  charm.

Adding implementation of fiveg_n3 interface in the UPF

---

src/charm.py
tests/unit/test_charm.py

- Adds dependency between the `routectl` and the `bessd`
- Adds additional log msg when workload service is restarted

Telco 583 fix race condition between bessd and routectl

---

README.md
metadata.yaml
src/charm.py
tests/unit/test_charm.py
tox.ini

Use the first version of the BESS rock for both `bessd` and `routectl` containers. The rock is smaller than upstream's image.
Use the PFCPIFACE rock for the `pfcp-agent` container. The rock is a bit larger than upstream because of `pebble`.

Use BESS rock for 'bessd' and 'routectl' and PFCPIFACE rock for 'pfcp-agent'

---

lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py

- Makes sure `routectl` service is restarted regardless of whether the pebble layer was changed
- Bumps `multus` library to the latest version

(Fix) Making sure routectl service always starts last

---

metadata.yaml
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Both `bessd` and `routectl` used the same image, so there was no sense in keeping them separated.
This PR removes dedicated `routectl` container and moves its workload to the `bessd` container. The `routectl` service starts before the `bessd`.

(Feat) Removing separate container for the routectl

---

config.yaml
requirements.txt
src/charm.py
test-requirements.txt
tests/unit/test_charm.py

By default, a `macvlan` interface will use the underlying host's interface with the default gateway. When following the tutorial, all interfaces share the same underlying host's interface.
However, it prevents connectivity with the outside world for real world scenario, like connecting a real `gNodeB`, or deploying the `UPF` on the edge, away from the core.
This change allows specifying what host interface to use for each multus interfaces, allowing the operator to expose the `UPF` to external networks.
When not specifying interfaces, `multus` interfaces will be created with the `bridge` plugin, separating the network traffic in different networks.

Allow specifying host interface to use for multus interfaces

---

src/charm.py

This change rollbacks the k8s_service_patcher object creation which is done by https://github.com/canonical/sdcore-upf-operator/pull/26.
We do not expect to get FileNotFoundError during KubernetesServicePatch object creation and we do not need to suppress it. In the unit tests kubernetes namespace file lookup is already mocked.

Rollback K8s Service patcher attribute

---

README.md

This PR corrects the charm name to be deployed in README.md which is indicating wrong charm.

Correcting charm name to be deployed

---

README.md
src/charm.py
tests/unit/test_charm.py

This PR implements CPU compatibility check. 
Check fails if the CPU doesn't support required extensions (currently it's `avx2` and `rdrand`). Failed check puts charm in Blocked status.
Check leverages the output of `lscpu` command. Alternatively we could use [py-cpuinfo](https://pypi.org/project/py-cpuinfo/), but it seems to be rarely maintained.

(Feat) Adding CPU compatibility check

---

.github/workflows/main.yaml
lib/charms/sdcore_upf/v0/fiveg_n4.py
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_provider_charm/metadata.yaml
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_requirer_charm/metadata.yaml
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_requirer.py

This PR adds a new `fiveg_n4`. 
The `N4` interface is typically used as a bridge between the User Plane and Control Plane. In Charmed 5G it will be primarily used to provide NMS with UPF information required to create a network slice.
**Reference:**
https://docs.google.com/document/d/1s3U82GTUZFJ9mEhiHig0oAl44F0fq3eQT2PNv1uV75g/edit

(Feat) Adding fiveg_n4 library

---

README.md
src/charm.py
tests/unit/test_charm.py

Exposes an external LoadBalancer service for the UPF, similar to https://github.com/canonical/sdcore-amf-operator/pull/24 for the AMF

Use LoadBalancer Service

---

lib/charms/sdcore_upf/v0/fiveg_n3.py
lib/charms/sdcore_upf/v0/fiveg_n4.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_requirer.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_requirer.py

Fixes a bug in `fiveg_n3` and `fiveg_n4` libs. 
Bug was caused by the fact that the provider side would set the app relation data, but requirer would pull the unit relation data.

(Fix) Fixing relation data

---

src/charm.py

Now that an externally accessible PFCP port is exposed and should be used instead, remove the legacy internal PFCP service port.
- #36 
- https://github.com/canonical/charmed-5g/pull/126

Remove internal PFCP port

---

config.yaml
lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py
tests/unit/test_charm.py

Adding optional configuration to set custom MTU sizes for UPF access and core interfaces. 
This branch is a replication of https://github.com/canonical/sdcore-upf-operator/pull/31 as that is having problem with the commit gpg verification.

Support custom MTU sizes

---

config.yaml
lib/charms/kubernetes_charm_libraries/v0/hugepages_volumes_patch.py
src/charm.py
tests/unit/test_charm.py

Integrate HugePages library in UPF and add configuration option. When enabled, bessd will use Hugepages of size 1Gi for a total of 2Gi.

Integrate HugePages library in UPF and add configuration option

---

src/charm.py
tests/unit/test_charm.py

[fix: Remove defers in config_changed](https://github.com/canonical/sdcore-upf-operator/commit/3bc00ada30509937bc414de6675f3ddae9ff0842)
Issue https://github.com/canonical/sdcore-upf-operator/issues/47 describes a problem where Multus tries to restart the pod
after applying NetworkAttachmentDefinitions, but the unit is stuck
for about 15 minutes in a failure loop.
The logs show that `config_changed` is reemited, causing the custom
`nad_config_changed` event to be emited, calling the Multus library.
At that point, Multus is unable to properly read the
NetworkAttachmentDefinitions and fails with an uncaught exception,
crashing the charm. The unit is then stuck in a loop until a timeout
occurs on the Juju controller side.
This change removes all defers that could happen in the …

fix: Remove defers in config_changed

---

src/charm.py
tests/unit/test_charm.py

In case something happens to cause our charm to go down without properly cleaning up the service, use `client.apply()` instead of client.create()`.
`apply()` will ensure the service configuration matches what is expected, but is OK if it already exists, unlike `create()` which will throw an error if the service already exists.
This will also prevent errors when scaling up (even though scaling isn't supported at this time).
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

fix: Protect against load balancer service existing

---

lib/charms/observability_libs/v0/juju_topology.py
lib/charms/observability_libs/v1/kubernetes_service_patch.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
requirements.txt

Updates the charm libs, and as a consequence removes plenty of warnings about deprecations.

chore: Update charm libs

---

src/charm.py
tests/unit/test_charm.py

Prevent scaling by blocking on non-leader units.
Also, add note about best-effort removal of the k8s service.

fix: Prevent scaling by blocking on non-leader units

---

src/charm.py
tests/unit/test_charm.py

This PR aims to fix #55. The fix catches the `TypeError` exception thrown when trying to access ingress information when MetalLB is not enabled or properly configured, allowing the charm to use the internal UPF hostname as expected.

fix: use internal UPF hostname when MetalLB is not available

---

tests/unit/test_charm.py
tox.ini

This PR aims to replace mock objects for `ops.model.Container.exec`, leveraging the new `ops.harness.handle_exec` method.

chore: Use handle_exec instead of mocking container exec method

---

src/charm.py
tests/unit/test_charm.py

Moves the state file that is used as a semaphore away from the persistent volume and into the container ephemeral storage so the test for configuration completed does not prevent config on restart
- N/A I have made corresponding changes to the documentation
- N/A I have added tests that validate the behaviour of the software
- N/A Any dependent changes have been merged and published in downstream modules
- N/A I have bumped the version of the library

fix: Reconfigure bessd on restart

---

src/charm.py
src/templates/upf.json.j2
test-requirements.txt
tests/unit/expected_upf.json
tests/unit/test_charm.py

Sets IP masquerade on the core interface of the UPF. This will automatically NAT UE traffic to appear to come from the UPF's core interface, making it simpler to integrate in existing networks.
The alternative is to have the core router know about the UE IP pool to be able to route back traffic towards the UPF.

feat: Set IP masquerade in the UPF configuration

---

.github/workflows/main.yaml
README.md
lib/charms/sdcore_upf_k8s/v0/fiveg_n3.py
lib/charms/sdcore_upf_k8s/v0/fiveg_n4.py
metadata.yaml
src/charm.py
test-requirements.txt
tests/unit/expected_upf.json
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_requirer.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_requirer.py
tests/unit/test_charm.py
tox.ini

Add -k8s as a suffix in both github and Charmhub name to follow [TE042](https://docs.google.com/document/d/1R0UzoPr3vvorhbBJYBz-5gZkTCTL2a9_R6xV8K4_i-8/edit) .
- Create new fiveg_n3 and fiveg_n4 libraries
- Pin macaroonbakery to 1.3.2 which installed by juju client indirectly through pytest_operator.
- The next protobuf version 4.21.0 has the breaking changes with the existing code
- https://protobuf.dev/news/2022-05-06/#python-updates

chore: Rename SD-Core charms by adding -k8s as a suffix

---

lib/charms/kubernetes_charm_libraries/v0/hugepages_volumes_patch.py
lib/charms/kubernetes_charm_libraries/v0/multus.py
src/charm.py
tests/unit/test_charm.py

This PR adds two validations to the UPF charm when enabling HugePages: the first is the support of the required CPU flags (`pdpe1gb`); the second is the capacity of enough HugePages (2Gi) on the K8S nodes. If the free HugePages (allocatable minus allocated) are not enough, the charm will remain in Waiting status.

fix: move to Blocked state when HugePages are not available

---

src/charm.py
tests/unit/test_charm.py

This PR aims to fix #74 . If Multus is not installed or enabled, move to Blocked state.

fix: move to Blocked state when Multus is disabled

---

config.yaml
src/charm.py
src/templates/upf.json.j2
tests/unit/expected_upf.json
tests/unit/test_charm.py

This adds `enable-hw-checksum` boolean configuration, set to `False` by default. This fixes an issue when using DPDK on interfaces that do not support hardware checksum offloading.
The current behavior is for BESS to crash with a cryptic error (`Error: rte_eth_dev_configure() failed`) when trying to setup the interfaces. This can happen when testing DPDK on virtual interfaces, but could also happen on any hardware NIC that does not support hardware checksums.

fix: Add 'enable-hw-checksum' configuration, disabled by default

---

config.yaml
tests/unit/expected_upf.json
tests/unit/test_charm.py

Changes the default value of `enable-hw-checksum` to True. Setting it to False breaks the simulation.

fix: Changing default value of hwcksum to true

---

tests/unit/test_charm.py

Fixes unit tests by adding missing `checks` section to the expected pebble plan.

fix: Adding checks section to the expected pebble plan

---

src/charm.py
tests/unit/test_charm.py

Instead of using an exception, which results in messages that are not helpful to the user (ie: hook failed), this change puts the charm into blocked state instead.
- N/A I have made corresponding changes to the documentation
- N/A Any dependent changes have been merged and published in downstream modules
- N/A I have bumped the version of the library

fix: TELCO-996 Use blocked status instead of throwing exception

---

config.yaml
requirements.txt
src/charm.py
src/charm_config.py
src/charm_state.py
tests/unit/test_charm.py

This PR aims to leverage Pydantic to validate charm config input parameters.
Support for `host-device` CNI type is added.
Config option `enable-hugepages` is removed and it is inferred from `upf-mode`.

feat: use Pydantic validator and support for new CNIs

---

src/charm.py

This PR aims to remove one useless getter function, residual from the introduction of Pydantic validation.

chore: Remove residual getter

---

lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
src/charm.py
tests/integration/test_integration.py
tests/unit/test_charm.py

Implement log forwarding via Pebble's new `log-target` spec. We use the `loki_push_api` charm relation to get the loki endpoint.

feat: implement log forwarding

---

src/charm.py
tests/unit/test_charm.py

The global constant called DEFAULT_FIELD_MANAGER is set to a default value which is `controller` refers the name of Juju controller that is not always correct.  Replacing  DEFAULT_FIELD_MANAGER with the charm name as it is the charm in charge of managing the field.

fix: Using charm name as DEFAULT_FIELD_MANAGER

---

src/charm.py
tests/unit/test_charm.py

If the `_exec_command_in_bessd_workload` timeout is the same as the timeout of the outer `while`, if the command hangs, it will never be retried.
NOTE:
Commands in the `up4.bess` script are not thread-safe, so after this change, the retry may fail anyway. Despite multiple tries, I wasn't able to provoke the command to hang. CI seems to be pretty good at it, hence the PR.

chore: Using default, 30s timeout for up4 config instead of 300s

---

src/charm.py

When `exec` (running command inside the container) command times out instead of failing, it raises `ChangeError` rather than the `ExecError`. 
This PR adds handling for the `ChangeError`.

chore: Catch ChangeError when configuring bess

---

tests/unit/test_charm.py

The charm conditionally sets the unit status (and does some other work, including observing) based on the result of setting up a configuration object during `__init__`. This isn't a practice that Charm Tech recommends, and it's one that currently works in production (if defer is not used) but is not supported by Harness (which [won't be changed, unfortunately](https://github.com/canonical/operator/issues/736)).
At the moment, the tests have a workaround where the harness charm is reinstantiated using private methods of both the harness framework and harness itself. This PR removes the reinstantiation, so that the private use is not required.
The actual change is pretty straightforward: it just waits until all the setup is complete (in particular, setting the config values) before calling …

refactor: use later `begin` rather than re-instantiating the harness charm 

---

lib/charms/sdcore_upf_k8s/v0/fiveg_n3.py
lib/charms/sdcore_upf_k8s/v0/fiveg_n4.py
pyproject.toml
src/charm.py
src/charm_config.py
src/dpdk.py
test-requirements.in
test-requirements.txt
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_provider_charm/src/charm.py
tests/unit/lib/charms/sdcore_upf/v0/test_charms/test_requirer_charm/src/charm.py
tests/unit/test_charm.py
tests/unit/test_dpdk.py
tox.ini

Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.

chore: Move to codespell and ruff 

---

src/charm.py
tests/unit/test_charm.py

This PR aims to fix #173. Status setting is removed from the try-except block during `__init__` and it now relies only on the `CollectStatus` event callback.
Unit tests requiring charm reinstatiation, as updated by #147, are updated evaluating the unit status.

fix: handle charm status only from CollectStatus event callback

---

src/charm.py

- Fixes https://github.com/canonical/sdcore-upf-k8s-operator/issues/172.
First of all, UPF charm initialize the Multus library without privilege. Then DPDK library patches the statefulset to privileged mode. Upon destroy, Multus library tries to get back the privilege by unpatching. However, statefulset is modified by DPDK library causes the API error reported in https://github.com/canonical/sdcore-upf-k8s-operator/issues/172.  If we initialize Multus library with privileged when the UPF is in DPDK mode, this issue is solved.
Tested by deploying UPF in DPDK mode and confirmed that the UPF is removed successfully without manual intervention.

fix: Initializing KubernetesMultusCharmLib with privileged mode

---

src/charm.py
tests/unit/test_charm.py

This PR fixes the invalid charm status displayed in a situation when the operator forgets to create required amount of HugePages. Before this change, the status would say "Incompatible CPU" instead of "Not enough HugePages".

fix: Fixes charm status when HugePages are not available

---

src/charm.py
tests/unit/test_charm.py

This PR aims to fix #233.
Main changes:
* handle `ExecError` when running `ip` command in the workload
* set charm status according to the presence of routes

fix: move to waiting status if routes are not set

---

src/charm.py
tests/unit/test_charm.py

This PR follows up on #220. After last change, `routectl` would still be started even if `bess` was not configured.
This PR fixes that problem by checking whether `bess` is configured before starting `routectl`

fix: Blocks starting routectl if bess is not configured

---

tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_requirer.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_requirer.py

PART 1: this PR only includes `tests/unit/lib` files
Remove `unittest` and use only `pytest` framework to run the unit tests.
Actions on this PR:
Add a `@pytest.fixture` for harness
Add a `@pytest.fixture` to setup patches and mocks
Continue using `Mock`, `call` and `patch` from the `unittest.Mock` library
Use `assert` instead of `self.assert...` methods

chore: use pytest

---

tests/unit/test_charm.py

FINAL PART: `TestCharm` class in `tests/unit/test_charm.py`
Remove `unittest` and use `pytest` framework to run the unit tests.
Now we have 460 lines less on this file
Actions on this PR:
- Add a `@pytest.fixture` for harness
- Add a `@pytest.fixture` to setup patches and mocks
- Continue using `Mock`, `call` and `patch` from the `unittest.Mock` library
- Use `assert` instead of `self.assert...` methods
- Parameterized test using `@pytest.mark.parametrize`

chore: use pytest in TestCharm class

---

src/charm.py
src/k8s_service.py
tests/unit/test_charm.py

Here we move the k8s specific code to its own class and file in order to simplify the charm class and centralize the k8s service management code in 1 place.

chore: move k8s service code to its own class/file

---

lib/charms/kubernetes_charm_libraries/v0/hugepages_volumes_patch.py
src/charm.py

Here we use the hugepages lib v0.6 which reduces complexity in the upf k8s charm. There is no more need for the charm to emit custom events that are listened to by the lib (which was unnecessarily complicated).
This PR has to be merged first:
- https://github.com/canonical/kubernetes-charm-libraries/pull/59

chore: use hugepages lib v0.6

---

tests/unit/fixtures.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n3_requirer.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_provider.py
tests/unit/lib/charms/sdcore_upf/v0/test_fiveg_n4_requirer.py
tests/unit/test_charm_bessd_pebble_ready.py
tests/unit/test_charm_collect_status.py
tests/unit/test_charm_config_changed.py
tests/unit/test_charm_pfcp_agent_pebble_ready.py
tests/unit/test_charm_remove.py

Now that scenario testing is built into ops we use ops.testing instead of directly calling scenario. Both have the same API. scenario still needs to be independently installed.

chore: use built-in testing from ops

---

README.md
charmcraft.yaml
src/templates/upf.json.j2
tests/unit/expected_upf.json

Bump the version of the rocks used to 1.5.0. Depends on https://github.com/canonical/sdcore-upf-bess-rock/pull/36

fix: Use 1.5.0 version of rocks

---

lib/charms/kubernetes_charm_libraries/v0/multus.py

If K8s `kube-apiserver` is not ready, lightkube calls can fails with `401 Unauthorized`. 
This PR improves error handling in the function checking Multus' availability. With this change, the code will not raise an exception on `401 Unauthorized`.

fix: Handles 401 Unauthorized when checking Multus availability

---

charmcraft.yaml
src/charm.py
src/charm_config.py
src/templates/upf.json.j2

Here we add a `log-level` configuration option with a reasonable default value (`info`). The allowed options are the same as in the workload: `debug`, `info`, `warn`, `error`, `fatal`, `panic`.
In most deployments, the log level should be set to `info` to ensure the log quantity is reasonable.

feat: add log-level configuration option

---

lib/charms/kubernetes_charm_libraries/v0/multus.py

Fetches the updated lib rather than doing changes locally.

fix: Updates Multus in the correct way

---

terraform/main.tf
terraform/variables.tf

This PR fixes [TELCO-1544](https://warthogs.atlassian.net/browse/TELCO-1544)
CONTEXT:
By default, Juju fetches charms with base matching the host OS. It means that when running Jammy, Juju won’t use latest charms, because we’ve changed the base to Noble. 
Adding an optional (as per CC006) config param base will allow using Noble (base should be set to `ubuntu@24.04`) regardless of the host OS.
Enforcing Noble on a Juju model configuration level is not an option, because it breaks COS integration (COS charms are not available in ubuntu@24.04
[TELCO-1544]: https://warthogs.atlassian.net/browse/TELCO-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Uses ubuntu@24.04 in TF module

---

src/charm.py

When `kube-apiserver` isn't ready, fetching list of K8s nodes fails with `Unauthorized` error. This fix handles such situation by catching the error and logging the relevant message rather than raising an error which puts the charm in the error state.

fix: Fixes Unauthorized error when listing K8s nodes

---

src/charm.py
src/dpdk.py
src/k8s_client.py
src/k8s_service.py
tests/unit/fixtures.py
tests/unit/test_charm_collect_status.py
tests/unit/test_dpdk.py

This PR implements a custom K8s client to catch ApiErrors centrally. 
The idea is to use a K8s client wrapped in a decorator handling ApiErrors. New k8s_client module implements a decorator and a Metaclass which is used to create a custom K8sClient and allows applying a decorator to every method of a base class (in this case a Lightkube Client).

fix: Implements a custom K8s client to catch ApiErrors centrally

---

src/charm.py
tests/unit/test_charm_collect_status.py

The comparison of the amount of allocatable hugepages failed if the amount was not exactly "2Gi" because we were using string comparisons.
This PR properly converts to integers before making the comparison and adds tests for multiple values.
The same fix is already merged on `v1.5`.

fix: Properly evaluate amount of hugepages

---

README.md
charmcraft.yaml

Bump the underlying upf workloads to the latest upstream release: 2.0.1.

chore: bump workload to v2.0.1

---

src/templates/upf.json.j2
tests/unit/config/expected_upf.json
tests/unit/config/expected_upf_no_masquerade.json

This PR removes an optional section from the configuration file that put a global throughput limit.

fix: Remove artificial throughput limit from configuration

---

.gitignore
charmcraft.yaml
src/charm.py
src/charm_config.py
tests/unit/test_charm_bessd_pebble_ready.py

This PR adds a new configuration option, `bess-http` to the UPF charm. The option accepts boolean values.
When enabled, the UPF will start and expose the bess HTTP server on port 5000.
A new service `besstl-http` is added to the `bessd` container plan. By default, the service [startup](https://documentation.ubuntu.com/pebble/reference/layer-specification/) is `disabled`.
When the configuration option is changed, the following operations are performed:
* if the new service startup value is `enabled` and the current status is `inactive`, the service is started
* if the new service startup value is `disabled` and the current status is `active`, the service is stopped
This logic is overridden when a service restart is forced by the caller of the service configuration function (the behaviour …

feat: add configuration to start BESS HTTP server

---

src/charm.py
tests/unit/test_charm_bessd_pebble_ready.py

The condition to decide if the bessd service needed to be restarted was wrong, and always true. Because of that, bessd was restarted every time update_status ran.
This PR fixes the issue and adds a test to cover that situation.

fix: Prevent constantly restarting bessd service
